<a href="https://colab.research.google.com/github/Rupasri0105/23CSBTB30/blob/main/arraytypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arry=np.array([2,5,7,3,8])
print(arry)
print(type(arry))

[2 5 7 3 8]
<class 'numpy.ndarray'>


In [2]:
array = np.array([3, 4, 5, 6, 7])
print("NumPy Array:", array)
print("Type:", type(array))
print("First element:", array[0])
print("Last element:", array[-1])
print("Sum of elements:", np.sum(array))
print("Mean of elements:", np.mean(array))

NumPy Array: [3 4 5 6 7]
Type: <class 'numpy.ndarray'>
First element: 3
Last element: 7
Sum of elements: 25
Mean of elements: 5.0


In [3]:
array = np.array([4, 8, 2, 3, 5])
print("Array:", array)
print("Type of array:", type(array))
print("First element:", array[0])
print("Last element:", array[-1])

Array: [4 8 2 3 5]
Type of array: <class 'numpy.ndarray'>
First element: 4
Last element: 5


In [5]:
array_1d = np.array([1, 2, 5, 7, 4])
print("1D Array:", array_1d)
print("Type of 1D Array:", type(array_1d))
print("Sum of elements:", np.sum(array_1d))
print("Mean of elements:", np.mean(array_1d))


1D Array: [1 2 5 7 4]
Type of 1D Array: <class 'numpy.ndarray'>
Sum of elements: 19
Mean of elements: 3.8


In [6]:
array_2d = np.array([[1, 6, 3], [2, 4, 6], [7, 3, 9]])
print("2D Array:\n", array_2d)
print("Type of 2D Array:", type(array_2d))
print("Sum of elements in 2D array:", np.sum(array_2d))
print("Transpose of 2D array:\n", np.transpose(array_2d))


2D Array:
 [[1 6 3]
 [2 4 6]
 [7 3 9]]
Type of 2D Array: <class 'numpy.ndarray'>
Sum of elements in 2D array: 41
Transpose of 2D array:
 [[1 2 7]
 [6 4 3]
 [3 6 9]]


In [7]:
array_3d = np.array([[[1, 4, 3], [4, 5, 3]],[[7, 5, 9], [12, 14, 16]]])
print("3D Array:\n", array_3d)
print("Type of 3D Array:", type(array_3d))
print("Sum of elements in 3D array:", np.sum(array_3d))
print("Shape of 3D array:", array_3d.shape)


3D Array:
 [[[ 1  4  3]
  [ 4  5  3]]

 [[ 7  5  9]
  [12 14 16]]]
Type of 3D Array: <class 'numpy.ndarray'>
Sum of elements in 3D array: 83
Shape of 3D array: (2, 2, 3)


In [8]:
# Creating a 4D array
array_4d = np.array([[[[1, 4], [2, 4]], [[5, 7], [7, 9]]],
                     [[[8, 10], [11, 13]], [[12, 14], [15, 17]]]])
print("4D Array:\n", array_4d)
print("Type of 4D Array:", type(array_4d))
print("Sum of elements in 4D array:", np.sum(array_4d))
print("Shape of 4D array:", array_4d.shape)


4D Array:
 [[[[ 1  4]
   [ 2  4]]

  [[ 5  7]
   [ 7  9]]]


 [[[ 8 10]
   [11 13]]

  [[12 14]
   [15 17]]]]
Type of 4D Array: <class 'numpy.ndarray'>
Sum of elements in 4D array: 139
Shape of 4D array: (2, 2, 2, 2)


In [9]:
array_a = np.array([2, 4, 6])
array_b = np.array([3, 5, 7])
array_add = array_a + array_b
print("\nAddition of Two Arrays:", array_add)
array_mul = array_a * array_b
print("Multiplication of Two Arrays:", array_mul)
array_div = array_b / array_a
print("Division of Two Arrays:", array_div)
array_pow = np.power(array_a, 2)
print("Element-wise Power (array_a^2):", array_pow)



Addition of Two Arrays: [ 5  9 13]
Multiplication of Two Arrays: [ 6 20 42]
Division of Two Arrays: [1.5        1.25       1.16666667]
Element-wise Power (array_a^2): [ 4 16 36]


In [10]:
sin_values = np.sin(array_a)
print("\nSin of array_a:", sin_values)
log_values = np.log(array_b)
print("Log of array_b:", log_values)
log2_values = np.log2(array_b)
print("Log base-2 of array_b:", log2_values)
exp_values = np.exp(array_a)
print("Exponential of array_a:", exp_values)



Sin of array_a: [ 0.90929743 -0.7568025  -0.2794155 ]
Log of array_b: [1.09861229 1.60943791 1.94591015]
Log base-2 of array_b: [1.5849625  2.32192809 2.80735492]
Exponential of array_a: [  7.3890561   54.59815003 403.42879349]
